/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiCloserRouteImport } from './routes/api/closer'
import { Route as ApiContactRouteImport } from './routes/api/contact'
import { Route as ApiPaymentRouteImport } from './routes/api/payment'
import { Route as ApiWebhookRouteImport } from './routes/api/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloserRoute = ApiCloserRouteImport.update({
  id: '/api/closer',
  path: '/api/closer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentRoute = ApiPaymentRouteImport.update({
  id: '/api/payment',
  path: '/api/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRoute = ApiWebhookRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/closer': typeof ApiCloserRoute
  '/api/contact': typeof ApiContactRoute
  '/api/payment': typeof ApiPaymentRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/closer': typeof ApiCloserRoute
  '/api/contact': typeof ApiContactRoute
  '/api/payment': typeof ApiPaymentRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/closer': typeof ApiCloserRoute
  '/api/contact': typeof ApiContactRoute
  '/api/payment': typeof ApiPaymentRoute
  '/api/webhook': typeof ApiWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/checkout'
    | '/api/closer'
    | '/api/contact'
    | '/api/payment'
    | '/api/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/checkout'
    | '/api/closer'
    | '/api/contact'
    | '/api/payment'
    | '/api/webhook'
  id:
    | '__root__'
    | '/'
    | '/api/checkout'
    | '/api/closer'
    | '/api/contact'
    | '/api/payment'
    | '/api/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiCloserRoute: typeof ApiCloserRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiPaymentRoute: typeof ApiPaymentRoute
  ApiWebhookRoute: typeof ApiWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/closer': {
      id: '/api/closer'
      path: '/api/closer'
      fullPath: '/api/closer'
      preLoaderRoute: typeof ApiCloserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment': {
      id: '/api/payment'
      path: '/api/payment'
      fullPath: '/api/payment'
      preLoaderRoute: typeof ApiPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiCloserRoute: ApiCloserRoute,
  ApiContactRoute: ApiContactRoute,
  ApiPaymentRoute: ApiPaymentRoute,
  ApiWebhookRoute: ApiWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
